### ISSUE TITLE
Plugin consideration

### ISSUE THREAD

**Issue by imeed166** [daledesilva/obsidian_project-browser#1]
I've watched your development logs, and I noticed that initially, you were searching for a plugin that would meet your requirements. After watching all the videos and reviewing the roadmap, the [Projects Plugin](https://github.com/marcusolsson/obsidian-projects) came to mind. This plugin offers a kanban view that allows you to rearrange notes based on metadata and move them between different states.

I want to clarify that my purpose in sharing this information is to provide you with some insights, not to devalue the time you have spent.

**Comment by daledesilva** [comment]
Thanks @imeed166 !
That indeed does cover several of the functionalities that I was looking for. Thanks for sharing :)
(Also, thanks for watching all the videos!!)

The Kanban view gets the closest to the kind of functionality and experience I'm creating, but there are a few significant UX approaches that don't align with the kind of experience I'd like to foster (and use for myself).

In general my design philosophy is to create a self-evident, zero setup, user experience so people can just write. The Obsidian community often focuses on high customisability at the expense of ease of use, and I think I can help plug that hole a little.
Note, this doesn't mean my plugin won't be customisable, but it will come at it with a different philosophy.

There are also a couple of key features that are priority for me.
- Navigating in and out of folders and projects with ease.
- The ability to create folders that appear as files so that multi-file documents can live alongside single-file documents more seamlessly.
