### ISSUE TITLE
Ability to drag tags from the "Tags" panel in Obsidian into the "tags" property list.

### ISSUE THREAD

**Issue by infinitefeatur3** [daledesilva/obsidian_project-browser#25]
Ability to drag tags from the "Tags" panel in Obsidian into the "tags" property list.

Would just be a nice quality of life feature when browsing available tags in other windows.

I'm not sure if it is even within the scope of this project or if another plugin handles this better.

Appreciate the plugin!

**Comment by infinitefeatur3** [comment]
Clicking to populate tags into the "tags" property from other Obsidian tag windows while the property list children is selected would be nice in addition, or instead.

**Comment by daledesilva** [comment]
Thanks for posting your idea @infinitefeatur3 !
Unfortunately, I think this interaction between windows is a little more involved than is worth the pay off at the moment.
It's also difficult because the plugin only works with the state property and shouldn't necessarily allow dragging just any tag into it.

I'm closing this issue for now, however, I do plan to allow auto populating any tags already used as state into the plugins settings to make this flow a bit easier.
